apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react-personal-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-personal-website
  template:
    metadata:
      labels:
        app: react-personal-website
    spec:
      containers:
      - name: frontend
        image: apaul18/frontend:latest
        ports:
        - containerPort: 3000
