apiVersion: v1
kind: Service
metadata:
  name: react-svc
  labels:
    app: react-personal-website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: react-personal-website
